- mks/views.py
> Adding the displaying of the chaired committees

- mks/api.py
- persons/api.py
- simple/management/commands/parse_candidates.py
added a new management command `parse_candidates` to add persons and roles
> Parsing election candidates

- docs/api/source/embed/index.rst
- mks/views.py
- static/html/demo-article.html
- templates/mks/tooltip.js
Copied the code of findAndReplaceDOMText to help replace only text on
the page leaving the rest unchanged.
Another small change is disabling the agendas data in the tooltip view
as it was slwoing the view.
> Fix the MK tooltip to modify only text elements

- knesset/settings.py
- user/migrations/0007_auto__add_usercustommetadata.py
- user/models.py
- user/urls.py
- user/utils.py
- user/views.py
need to add the opensubs settings, in local_settings:
(set the fb_secret accordingly)
LOGIN_REDIRECT_TARGETS = {
'opensubs': {
'parent_location_href': 'https://osubs.org:9000/',
'redirect_to_url': 'https://osubs.org/#/login/',
'fb_secret': ''
}
}
> support storing arbitrary data for facebook apps

- laws/api.py
issue should not be considered as solved. 
this only solves the issue for filtering dates in the  votes page.
long term solution should be to reuse the same piece of filtering code in the API and the page.
> issue #172: an _extremely_  partial remediation. 

- mks/views.py
- templates/mks/parties_members.html
A better way to display the MKs.
> better order for the parties

- static/js/ok-suggest.js
I think this zoom rate is a good balance
> Issue #368 - Decreased zoom factor to half of what it was.

- committees/api.py
- committees/migrations/0018_auto__add_field_committee_hide.py
- committees/models.py
- committees/views.py
- simple/management/commands/syncdata.py
- templates/committees/committee_list.html
fixes #390 
also - added logging using okscraper framework for syncdata command
> fix committees and add logging for syncdata

- requirements.txt
> fix requirements - set django-debug-toolbar to version less then 1.4

- .gitignore
- docs/devel/source/css_docs.rst
- package.json
- static/css/app.css
The css output from less compilation is different between less versions
To make sure we have consistent results, I changed the less installation and run procedures to use the same node.js and less versions.
Documentation is updated as well.
> Make css files more consistent

- agendas/models.py
- agendas/queries.py
- mks/managers.py
> agendas should show only current knesset mks and parties

- mks/admin.py
- templates/mks/member_detail.html
> issue #369 when changing MK details on the admin, the mk page does not change because of cache

- plenum/management/commands/parse_plenum_protocols_subcommands/parse.py
- requirements.txt
> fix plenum protocol parser

- committees/migrations/0020_auto__add_field_committee_knesset_id__add_field_committee_knesset_type.py
- committees/migrations/0021_auto__add_field_committeemeeting_datetime__add_field_committeemeeting_.py
- committees/models.py
- committees/scrapers.py
- deploy/crontab.txt
- docs/devel/source/scraping/committees.rst
- docs/devel/source/scraping/index.rst
- laws/scrapers.py
- requirements.txt
- simple/management/commands/syncdata.py
- simple/scrapers/__init__.py
- simple/scrapers/sources.py
* using the okscraper framework
* get some more data which is only available via the knesset API
* more reliable then html scrapers
* standardized knesset scrapers which will make writing other knesset scrapers much easier
need to add cronjob:
* manage.py okscrape committees CommitteeMeetingsMultiPageScraper --dblog
> #490 - committee: added new scrapers for committees and meetings (using knesset API)

- templates/about.he.html
Delete the following -
- Credit to Ampiric
- All links to the Open Knesset Googel Group
- Mail to media, it was actually mail to the Knesset itself, and not
Open Knesset
-Data sources section (We created a new page for this already)
Updated  Media section
> Update about page

- laws/admin.py
- laws/models.py
> 506 - some votes show None in for/against/abstain counts

- laws/management/commands/scrape_votes.py
fixes #546 - make sure vote id is not changed when recreating
partially fixes #547 - added options to scrape_votes management command to allow validating and partially fixing invalid votes data (some errors are fixed automagically but others require manual intervention)
> 546 547 vote scraper improvements

- templates/laws/_public_opinion_partial.html
- templates/laws/bill_detail.html
> seperate public opinion partial and remove for now

- docs/devel/source/feature_toggle.rst
- docs/devel/source/index.rst
- knesset/settings.py
- mks/views.py
- requirements.txt
- close #567 
- Adding a feature toggle framework (Waffle) and documentation
> Bugfix 567 remove by graph

- committees/management/commands/scrape_committees.py
- requirements.txt
based on @noamelf 's PR #576 with minor fix to requirements
> Improved scrape_committees command to fetch sub-committees

- committees/admin.py
- committees/tests/test_committee_meeting_detail_view.py
- committees/views.py
- events/admin.py
- events/scrapers.py
- knesset/settings.py
- laws/admin.py
- laws/forms.py
- laws/models.py
- laws/templatetags/bills_tags.py
- lobbyists/admin.py
- mks/admin.py
- mks/management/commands/recalc_mks_bill_stats.py
- mks/management/commands/update_mks_users.py
- mks/views.py
- persons/admin.py
- requirements.txt
- user/admin.py
- partial fix #594
- really fix #391 
- small pep8 changes
- adding ability to import/export to excel/csv to most admin screens
> hotfix for missing code in pr (adding removing mk) and more issues

- kikar/static/kikar/js/homepage.js
- kikar/urls.py
- kikar/views.py
- mks/management/commands/recalc_mks_bill_stats.py
- templates/robots.txt
- close #604 
- add kikar fetching urls to robots disallowed
- compile handlbars template only once
- protect from empty list in template
- fix error message typo
- protect from invalid request to kikar url (raise 400)
> Fix 604 kikar issues

- mks/management/commands/recalc_mks_bill_stats.py
- fix typo that fails recalc bill stats command
> fix typo that fails recalc bill stats command

- committees/tests/test_committee_meeting_detail_view.py
- committees/views.py
- knesset/exceptions.py
> close #616, sanitize edit committee details bills mks input

- kikar/static/kikar/js/kikar.js
> facebook status from kikar handling the case where there is no 'read more' available

- laws/api.py
- laws/tests/test_api_v2.py
- close #638 
Parsing the date_to param with dateutil instead of manually
> close #638 api breaks on date formatting of to_date

- laws/management/commands/scrape_votes.py
- laws/models.py
- simple/scrapers/management.py
> #547 - fix the votes data validation management command to use html data (as api is unreliable)

- knesset/technical_services/csv_writer.py
- mks/management/commands/committee_attendance_report.py
- mks/managers.py
- mks/models.py
- requirements.txt
###
Adding a csv attendance report for @morchickit to answer reporters
> Attendance report

- mks/management/commands/committee_attendance_report.py
- mks/management/commands/committee_detailed_attendance_report.py
- mks/models.py
> detailed attendance report

- mks/models.py
> fix groupby to use set - get just one committee of each type

- laws/tests/test_bills_list_view.py
> close #649

- templates/site_base.html
I'll probably need to replace the image once we get one, but this is good enough to start with, especially since I mainly want to start experimenting with facebook/linkedin/twitter/whatsapp apis and bots
I'll open another task for advanced sharing (instant article , share from site etc)
> Facebook share

- templates/site_base.html
> full link to image, change twitter format for full summary

- committees/tests/test_committee_meeting_detail_view.py
- committees/views.py
- close #680 
- Add support for alias name for lobbyist adding and removing in committee meeting view
> close #680 adding support for lobbyist alias name

- less/footer.less
- static/css/app.css
- templates/site_base.html
> Removed english blurb in footer

- mks/views.py
> refactored p => party so I can understand what's going on

- committees/models.py
- committees/tests/base.py
- committees/tests/test_committee_detail_view.py
- committees/tests/test_committee_meeting_detail_view.py
- committees/views.py
if was replacement or chairperson
- Resolves #724
> resolve #724 non current mk appears in committee page

- committees/models.py
- committees/views.py
- knesset/settings.py
- laws/views.py
- links/templatetags/links_tags.py
> minor fix for mistaking in members links optimizations

- accounts/models.py
- auxiliary/management/commands/iterdumpdata.py
- laws/templatetags/laws_tags.py
- lobbyists/scrapers/lobbyists_index.py
- presence/BeautifulSoup.py
- simple/management/commands/mk_info_html_parser.py
- simple/management/commands/parse_gov_legislation_comm.py
- simple/management/commands/syncdata.py
- video/management/commands/sub_commands/DownloadCommitteesVideos.py
- video/management/commands/sub_commands/UpdateCommitteesVideos.py
- video/utils/youtube.py
- Changed deprecated logging setup, Added better logger.execption handler
> Exception logging 1

- knesset/settings.py
- presence/PresenceChecker.sh
- Fix problem in presence bash script (would fail if we did got data from knesset :(
- Silence opbeat and requests debug logging
> Fix problem in presence and better logs

- committees/admin.py
- committees/migrations/0024_auto__chg_field_protocolpart_body__chg_field_protocolpart_header__chg_.py
- committees/models.py
- events/scrapers.py
- resolves #740 (At least trying)
Added a basic admin for protocol parts
Fixed missing "blank " on some nullable fields
> Person event calendar exception handling and protocol parts issues

- templates/about.he.html
- Resolves #745 
- Changed "Suiteable+as+first+task" to "Starter"
> Change to correct 'Starter' label. fix#:745

- events/views.py
- plenum/management/commands/parse_plenum_protocols_subcommands/download.py
- simple/constants.py
- simple/management/commands/parse_future_committee_meetings.py
- Resolves #749 (Hopefully, since I can't check locally)_
- also some more exception logging fixing in plenum scraper
> resolve broken future events scraper

- simple/constants.py
> fix meeting constants

- auxiliary/tests/test_internal_links.py
- knesset/urls.py
- templates/help_page.he.html
- templates/main.he.html
- templates/site_base.html
> Move home page to be current help page

- templates/about.he.html
- Resolves #747 
- Changed Open Congress to GovTrack
> Change Open Congress to GovTrack. fix#:747

- deploy/crontab.txt
- knesset/browser_cases.py
- knesset/browser_test_runner.py
- laws/admin.py
- laws/enums.py
- laws/helpers.py
- laws/management/commands/rescrape_missing_data_votes.py
- laws/management/commands/scrape_votes.py
- laws/models/vote.py
- mks/admin.py
- mks/managers.py
- mks/models.py
- simple/constants.py
- simple/management/commands/syncdata.py
- simple/scrapers/management.py
- Resolves #760 (Would need to add a cronjob also)
- Resolves #758 Vote scraper issues
- Resolves #756 missing votes data filter
- Some admin improvements in various models 
- Massive cleanup of syncdata (still lots to do remaining)
> Mostly vote issues

- knesset/urls.py
- laws/models/law.py
- laws/models/vote.py
> Redirect main page would return 302 (since temp)

- docs/devel/source/environment/index.rst
- docs/devel/source/environment/linux.rst
- docs/devel/source/environment/osx.rst
- docs/devel/source/environment/windows.rst
Two small issues in the documentation
- Fixes a typo from git hub to GitHub
- Explicitly mentions a required pip version
> Setup documentation changes

- knesset/browser_test_runner.py
- persons/management/commands/update_gov_roles.py
- plenum/urls.py
- plenum/views.py
- simple/constants.py
- simple/management/commands/syncvotes.py
- simple/parsers/parse_committee_members.py
- simple/parsers/parse_knesset_bill_pdf.py
try to fix saucelabs tests + Pep8 + removing old code
> try to fix saucelabs tests + Pep8 + removing old code

- auxiliary/tests/test_internal_links.py
> Fix test fixture loading to work on windows

- docs/devel/source/environment/tests_db.rst
> Remove django debug toolbar documentation

- committees/tests/base.py
- committees/tests/test_committee_detail_view.py
- completes review on #783 
- refactor some tests to use verify methods.
> refactor tests of committee topics.

- committees/tests/base.py
- simple/management/commands/download_data.py
- simple/management/commands/dump_file_data.py
- simple/management/commands/load_file_data.py
- simple/management/commands/syncdata.py
new separated commands:
- simple/management/commands/download_data.py
- simple/management/commands/dump_file_data.py
- simple/management/commands/load_file_data.py
> Separate lots of unkown/unused/rarely used functionality from syncdata to dedicated commands

- laws/models/proposal.py
> fixes #796 - proposals should be ordered by date

- apis/resources/base.py
- laws/api.py
> fix tastypie custom csv serializer

- docs/devel/source/scraping/committees.rst
- docs/devel/source/scraping/index.rst
- requirements.txt
> update to latest knesset-data dependencies + update documentation regarding scrapers

- .gitignore
- auxiliary/tag_suggestions/__init__.py
- committees/models.py
- committees/views.py
- deploy/crontab.txt
- events/scrapers.py
- ok_tag/tag_suggestions.py
- simple/management/commands/syncdata.py
fix #840 
Allowing syncdata command to run presence alone if we need to
Fixing uploading a protocol in meeting view didn't pass mks to parse part of 
Various cleanups
part of fixing #833
> minor cleanup and adaptions + a part of #833
